#!/bin/sh

print_usage (){
echo “USAGE:”
echo -e “\t $0 inputfile.svg [outputfile.pdf]“
}

build_pdf_filename(){
echo “$1″ | sed -e ‘s@.svg@.pdf@g’
}

if [ "$1" = "" ]
then
print_usage
exit
fi

if [ "$2" = "" ]
then
OUTPUT=`build_pdf_filename $1`
else
OUTPUT=$2
fi

echo “Converting $1 to PDF…”

inkscape -z -T -A $OUTPUT $1