#!/bin/bash -l
#PBS -l nodes=1:ppn=1
#PBS -l walltime=00:02:00
#PBS -l pmem=2kb
#PBS -j oe
#PBS -N Prime_0
#PBS -o log/0
echo "Running job on $HOST - " ‘date‘
cd ~/infof404/2
module load openmpi/1.4.3/gcc/4.6.1
make O=3 nocolor=true
mpirun run/ulamSpiralGenerator 1000 --speed
echo "Done"
