#!/bin/bash -l
#PBS -l nodes=1:ppn=1
#PBS -l walltime=00:10:00
#PBS -l pmem=1gb
#PBS -j oe
#PBS -N Prime_1
#PBS -o log/1
echo "Running job on $HOST - " ‘date‘
cd ~/infof404/2
module load openmpi/1.4.3/gcc/4.6.1
make O=3 nocolor=true
mpirun run/ulamSpiralGenerator 100000000 --speed
echo "Done"
